# Build stage : build the application
FROM yidoughi/nodepine AS builder

WORKDIR /build
COPY package.json pnpm-lock.yaml ./
COPY . .

RUN npm install -g pnpm \
    && pnpm install \
    && pnpm run build && ls -la

# Production stage : keep only the necessary dependencies for production
FROM node:slim AS base-production

WORKDIR /dist

COPY --from=builder /build/package.json ./package.json
RUN npm i -g pnpm && pnpm install --production && npm cache clean -f


# Production stage : build the final image with user 1001
FROM yidoughi/nodepine AS production

WORKDIR /app

ENV PATH="/usr/local/bin/ollama:$PATH" \
    HOME="/home/ollama" \
    PROXY_HOME=${PROXY_HOME:-"/app"} \
    OLLAMA_HOME="/home/ollama/.ollama" \
    OLLAMA_TARGET_MODEL=${OLLAMA_TARGET_MODEL:-"gemma:2b"} \
    OLLAMA_PORT=${OLLAMA_PORT:-"11434"} \
    OLLAMA_HOST=${OLLAMA_HOST:-"http://localhost:"$OLLAMA_PORT} \
    PROXY_PORT=3000 \
    PROXY_CERTS_DIR="/app/certs" \
    NODE_ENV=${NODE_ENV:-"production"}

COPY --from=builder --chown=1001:1001  /build/dist ./dist
COPY --from=builder --chown=1001:1001  /build/package.json ./
COPY --from=builder --chown=1001:1001  /build/certs ./certs

COPY --from=base-production --chown=1001:1001  /dist/node_modules ./dist/node_modules

USER 1001

CMD [ "node", "/app/dist/main.js" ]