apiVersion: v1
kind: Service
metadata:
  name: proxyllama-ingress
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s-controller
  type: LoadBalancer
  ports:
    - name: proxyllama
      protocol: TCP
      port: 8080
      targetPort: 3000
    - name: ollama
      protocol: TCP
      port: 11435
      targetPort: 11434