---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: kustomization

resources:
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml
