apiVersion: v1
kind: Service
metadata:
  name: proxyllama
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: proxyllama
  ports:
    - protocol: TCP
      name: proxyllama
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - protocol: TCP
      name: ollama
      port: 11434
      targetPort: 11434
      nodePort: 30001     
  type: LoadBalancer